name: Create release artifacts
on:
  push:
    branches: [ci]
    tags:
      - "v*"

jobs:
  create-release-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Get repo to build
      uses: actions/checkout@v2 # runner use this repo
    - name: setup Node.js # runner uses node runtime to build source into app
      uses: actions/setup-node@v1
      with:
        node-version: '17'
    - name: Install dependencies
      run: npm install
    - name: Build the app
      run: npm run build --if-present

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        release: true
        name: mainclient-${{ startsWith(github.ref, 'refs/tags/v')}}
        path: |
          dist
          !dist/**/*.md