name: Node.js CI

on:
  push:
    branches: [ ci ]
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: |
         npm ci
         echo ${{ steps.get_version.outputs.VERSION }}
      - name: Build app
        id: built-app
        run: npm run build --if-present

      - name: testing accessing
        id: test-accessing-artifacts
        run: | 
          echo ${{ steps.built-app.output.artifacts }}
          echo ${{ steps.get_version.outputs.VERSION }}
          echo $GITHUB_BASE_REF
          echo $GITHUB_REF
          echo $GITHUB_REF_TYPE
          echo $GITHUB_ACTION_PATH
          echo $GITHUB_ACTION_REPOSITORY
          echo $GITHUB_EVENT_PATH
          echo $GITHUB_JOB
          echo $GITHUB_WORKSPACE
      # - name: try upload to releases
      #   uses: actions/upload-artifact@v2 
      #   with:
      #     name: test3 #-${{ steps.get_version.outputs.VERSION }}
      #     path: "dist/*"

      # - name: Upload to releases
      #   uses: AButler/upload-release-assets@v2.0
      #   with:
      #     files: dist/*
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}