name: Node.js CI

on:
  push:
    branches: [ ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build --if-present

      - name: try upload to releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'ref/tags/')
        with:
          files: dist/*
          draft: false
          prerelease: false
          tag_name: github.ref
          token: ${{ secrets.GITHUB_TOKEN }}
